# YAML File for SMPy/KaiserSquires/run.py  

# General settings
general:
  # Paths
  input_path: "/home/wslgeorgios/SMPy/notebooks/forecast_lum_annular.fits"
  output_directory: "/home/wslgeorgios/SMPy/notebooks/output_testing/"
  output_base_name: "simulation_testing"  # Base name for output files
  save_fits: false  # Save output as FITS file 

  # Map creation settings
  method: "kaiser_squires"  # Convergence map method
  create_snr: false  # Set to false if you don't want to create the SNR map

  # Common parameters
  resolution: 0.4  # Pixel resolution of the map in arcminutes
  ra_col: 'ra'
  dec_col: 'dec'
  g1_col: 'g1_Rinv'
  g2_col: 'g2_Rinv'
  weight_col: 'weight'
  mode: ['E']  # For both E and/or B modes


# Convergence Map Settings
convergence:
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Convergence Map'
  gridlines: true

  # Optional Plotting
  vmax: null
  vmin: null
  smoothing: 'gaussian_filter' # Current options: null or 'gaussian_filter'
  gaussian_kernel: 2
  cluster_center: null # Options for marker: null (do nothing), 'auto' (center of boundaries), {"ra_center": val, "dec_center": val} (custom coords)


# SNR Map Settings
snr:
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Signal-to-Noise Map'
  gridlines: true
  num_shuffles: 100  # Number of shuffles for SNR calculation

  # Optional Plotting
  vmax: null
  vmin: null
  smoothing: 'gaussian_filter' # Current options: null or 'gaussian_filter'
  gaussian_kernel: 2
  cluster_center: null # Options for marker: null (do nothing), 'auto' (center of boundaries), {"ra_center": val, "dec_center": val} (custom coords)
