# YAML File for SMPy Configuration

# General settings
general:
  # Coordinate system specific settings
  coordinate_system: "radec"  # Options: "radec" or "pixel"
  radec:
    resolution: 0.4  # Resolution in arcminutes
  pixel:
    downsample_factor: 170  # Factor to downsample pixel grid
  
  # Paths
  input_path: "/home/wslgeorgios/SMPy/examples/data/forecast_lum_annular.fits"
  output_directory: "/home/wslgeorgios/SMPy/examples/outputs/"
  output_base_name: "simulation_testing"  # Base name for output files
  save_fits: false  # ***BROKEN FEATURE*** Save output as FITS file 

  # Map creation settings
  method: "kaiser_squires"  # Convergence map method
  create_snr: true  # Set to false if you don't want to create the SNR map

  # Common parameters
  coord1: 'ra'
  coord2: 'dec'
  g1_col: 'g1_Rinv'
  g2_col: 'g2_Rinv'
  weight_col: 'weight' # Provide null if you have no weights
  mode: ['E']  # Can be ['E'], ['B'], or ['E', 'B']

# Convergence Map Settings
convergence:
  # Smoothing configuration
  smoothing:
    type: 'gaussian'  # Options: 'gaussian' or null
    sigma: 2.0  # Gaussian filter sigma parameter

  # Plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Convergence Map'
  gridlines: true

  # Optional Plotting
  vmax: null
  vmin: null
  threshold: null # Threshold for marking peaks in the convergence map (float or null)
  verbose: null # Print out table of peak values and positions
  cluster_center: null  # Options: null (do nothing), 'auto' (center of image), or 
                        # {'ra_center': float, 'dec_center': float} for radec (decimal degrees)
                        # {'x_center': float, 'y_center': float} for pixel (pixel coordinates)

# SNR Map Settings
snr:
  # Type of SNR map
  shuffle_type: 'spatial' # Options: 'spatial' or 'oritentation'

  # Smoothing configuration
  smoothing:
    type: 'gaussian'  # Options: 'gaussian' or null (null is not reccomended for S/N maps)
    sigma: 2.0  # Gaussian filter sigma parameter

  # Plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Signal-to-Noise Map'
  gridlines: true
  num_shuffles: 100  # Number of shuffles for SNR calculation

  # Optional Plotting
  vmax: null
  vmin: null
  threshold: null # Threshold for marking peaks in the convergence map (float or null)
  verbose: null # Print out table of peak values and positions
  cluster_center: null    # Options: null (do nothing), 'auto' (center of image), or 
                          # {'ra_center': float, 'dec_center': float} for radec (decimal degrees)
                          # {'x_center': float, 'y_center': float} for pixel (pixel coordinates)