# YAML File for SMPy Configuration

# General settings
general:
  # Input/Output paths
  input_path: "/home/wslgeorgios/SMPy/examples/data/forecast_lum_annular.fits"
  output_directory: "/home/wslgeorgios/SMPy/examples/outputs/"
  output_base_name: "simulation_testing"
  save_fits: false  # Currently not supported

  # Coordinate system settings
  coordinate_system: "radec"  # 'radec' or 'pixel'
  radec:
    resolution: 0.4  # In arcminutes
    coord1: 'ra'    # RA column name
    coord2: 'dec'   # Dec column name
  pixel:
    downsample_factor: 170  # Grid reduction factor
    coord1: 'X_IMAGE_se'    # X column name
    coord2: 'Y_IMAGE_se'    # Y column name
  
  # Data columns
  g1_col: 'g1_Rinv'
  g2_col: 'g2_Rinv'
  weight_col: 'weight'  # Set to null if no weights
  
  # Analysis settings
  method: "kaiser_squires"
  create_snr: true  # Whether to create SNR map
  mode: ['E']  # ['E'], ['B'], or ['E', 'B']

# Convergence Map Settings
convergence:
  smoothing:
    type: 'gaussian'  # 'gaussian' or null
    sigma: 2.0        # Smoothing scale
    
  # Basic plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'auto'  # 'auto', null, or custom string
  ylabel: 'auto'  # 'auto', null, or custom string
  plot_title: 'Convergence Map'
  gridlines: true
  
  # Advanced plotting
  vmax: null
  vmin: null
  threshold: null    # Peak detection threshold
  verbose: null      # Print peak information
  cluster_center: null  # null, 'auto', or {ra/x_center: float, dec/y_center: float}

# SNR Map Settings
snr:
  shuffle_type: 'spatial'  # 'spatial' or 'orientation'
  num_shuffles: 100       # Number of random realizations
  
  smoothing:
    type: 'gaussian'  # 'gaussian' or null (null not recommended for SNR)
    sigma: 2.0        # Smoothing scale
  
  # Basic plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'auto'  # 'auto', null, or custom string
  ylabel: 'auto'  # 'auto', null, or custom string
  plot_title: 'Signal-to-Noise Map'
  gridlines: true
  
  # Advanced plotting
  vmax: null
  vmin: null
  threshold: null    # Peak detection threshold
  verbose: null      # Print peak information
  cluster_center: null  # null, 'auto', or {ra/x_center: float, dec/y_center: float}