# YAML File for SMPy Configuration

# General settings
general:
  # Paths
  input_path: "/home/wslgeorgios/SMPy/examples/data/forecast_lum_annular.fits"
  output_directory: "/home/wslgeorgios/SMPy/examples/outputs/"
  output_base_name: "simulation_testing"  # Base name for output files
  save_fits: false  # Save output as FITS file 

  # Map creation settings
  method: "kaiser_squires"  # Convergence map method
  create_snr: true  # Set to false if you don't want to create the SNR map

  # Common parameters
  resolution: 0.4  # Pixel resolution of the map in arcminutes
  ra_col: 'ra'
  dec_col: 'dec'
  g1_col: 'g1_Rinv'
  g2_col: 'g2_Rinv'
  weight_col: 'weight' # provide null if you have no weights
  mode: ['E']  # For both E and/or B modes

# Convergence Map Settings
convergence:
  # Smoothing configuration
  smoothing:
    type: 'gaussian'  # Current options: 'gaussian' or null
    sigma: 2.0  # Gaussian filter sigma parameter

  # Plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Convergence Map'
  gridlines: true

  # Optional Plotting
  vmax: null
  vmin: null
  cluster_center: null # Options for marker: null (do nothing), 'auto' (center of boundaries), {"ra_center": val, "dec_center": val} (custom coords)
  threshold: null # Threshold for marking peaks in the convergence map (float or null)
  verbose: false # Print out table of peak values and positions

# SNR Map Settings
snr:
  # Type of SNR map
  shuffle_type: 'spatial' # Options: 'spatial' or 'oritentation'

  # Smoothing configuration
  smoothing:
    type: 'gaussian'  # Current options: 'gaussian' or null (not reccomended for S/N maps)
    sigma: 2.0  # Gaussian filter sigma parameter

  # Plotting
  figsize: [20, 10]
  cmap: 'magma'
  xlabel: 'Right Ascension (deg)'
  ylabel: 'Declination (deg)'
  plot_title: 'Signal-to-Noise Map'
  gridlines: true
  num_shuffles: 100  # Number of shuffles for SNR calculation

  # Optional Plotting
  vmax: null
  vmin: null
  cluster_center: null # Marker: null (no marker), 'auto' (center of boundaries), {"ra_center": float, "dec_center": float} (custom coords)
  threshold: null # Threshold for marking peaks in the convergence map (float or null)
  verbose: false # Print out table of peak values and positions